spring.application.name=HealthApp
# Setari pentru baza de date in memorie H2
spring.datasource.url=jdbc:h2:mem:healthapp_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Creeaza automat tabelele pe baza claselor tale (ex: Trasabilitate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configurare MQTT
mqtt.broker.url=tcp://broker.hivemq.com:1883
mqtt.client.id=health-app-client
mqtt.topic=spital/teleasistenta/senzori
mqtt.qos=2
